Wapi user in group
sourque/aeacus pull request #63
Opened 2020-08-17 04:17 UTC by safinsingh

2020-08-17 04:21 UTC, aaditgupta21 approved these changes

2020-08-17 06:57 UTC, sourque requested changes

2020-08-17 06:57 UTC, sourque commented on src/checks_windows.go
> +	users, err := wapi.LocalGroupGetMembers()
Hmm...

2020-08-18 18:46 UTC, sourque approved these changes

2020-08-18 18:47 UTC, merged